WIP on CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,7 @@ env:
     -x
   # Override the default rust compilation profile made in `build.py`,
   # We prefer using one that is more fit to the CI.
-  CARGO_PROFILE: integration
+  CARGO_PROFILE: ci
   cargo-exclude-unused-crates: >-
     --exclude=libparsec_bindings_jni
     --exclude=libparsec_bindings_web
@@ -39,16 +39,15 @@ jobs:
     name: ⭐ CI is happy ⭐
     needs:
       - check-quality-assurance
-      - rust-prebuild-matrix
       - test-python-matrix
       - test-rust-matrix
-      - test-web-app
-      - test-wasm
+      # - test-web-app
+      # - test-wasm
     runs-on: ubuntu-latest
     if: always()
     steps:
       # The Needs context value contains only:
-      # - the final state a jobs (if it fail or not)
+      # - the final state a jobs (if it fails or not)
       # - it's output (actually none of our jobs are configuring outputs variable)
       #
       # https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
@@ -93,13 +92,8 @@ jobs:
         with:
           node-version: ${{ env.node-version }}
 
-      - uses: ./.github/actions/setup-rust
-        with:
-          version: ${{ env.rust-version }}
-          components: rustfmt, clippy
-          cache-key: ${{ github.job }}
-          os: ubuntu-20.04
-        timeout-minutes: 10
+      - uses: actions-rust-lang/setup-rust-toolchain@v1.3.4
+        if: steps.python-changes.outputs.run == 'true'
 
       - name: Debug installed tools
         run: |
@@ -112,9 +106,6 @@ jobs:
           rustc --version
           whereis cargo
           cargo --version
-
-      - name: Debug rust cache
-        run: ls -la ~/.cargo/{.,bin,git,registry} target || true
 
       - name: Check Commit Signature
         run: python .github/scripts/check_commit_signature.py
@@ -133,6 +124,11 @@ jobs:
           git fetch origin master
           python .github/scripts/check_newsfragments.py ${{ github.head_ref }}
 
+      - name: Patch pre-commit for line-ending
+        run: |
+          sed -i '/id: mixed-line-ending/a\        args: [ --fix=lf ]' .pre-commit-config.yaml
+          cat .pre-commit-config.yaml
+
       - name: Install project (needed for mypy check)
         run: poetry install -E core -E backend
 
@@ -140,107 +136,10 @@ jobs:
         timeout-minutes: 30
 
   ##############################################################################
-  #                            🦀 Rust Pre-build                               #
-  ##############################################################################
-  rust-prebuild-matrix:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: 🐧 Linux
-            # All linux jobs must run the same ubuntu version to avoid Rust caching issues !
-            os: ubuntu-20.04
-          - name: 🍎 macOS
-            os: macos-12
-          - name: 🏁 Windows
-            os: windows-2022
-    name: '${{ matrix.name }}: 🦀 Rust Prebuild 🏗️'
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin v3.1.0
-
-      - uses: ./.github/actions/paths-filter
-        id: changes
-
-      - name: Check modified path that require rust-ci run
-        id: rust-changes
-        if: >-
-          steps.changes.outputs.rust == 'true'
-          || steps.changes.outputs.python == 'true'
-          || steps.changes.outputs.rust-ext == 'true'
-          || github.ref == 'refs/heads/master'
-        run: echo "run=true" >> $GITHUB_OUTPUT
-        shell: bash
-
-      - uses: ./.github/actions/setup-rust
-        id: rust-cache
-        if: steps.rust-changes.outputs.run == 'true'
-        with:
-          version: ${{ env.rust-version }}
-          cache-key: integration
-          os: ${{ matrix.os }}
-        timeout-minutes: 10
-
-      # Pyo3 need additional configuration on MacOS to be manually build
-      # see https://pyo3.rs/v0.17.3/building_and_distribution.html#macos
-      - name: (🍎 macOS) Configure cargo for PyO3
-        if: >-
-          steps.rust-changes.outputs.run == 'true'
-          && steps.rust-cache.outputs.cache-hit != 'true'
-          && startsWith(matrix.os, 'macos-')
-        shell: bash
-        run: |
-          set -eux
-          set -o pipefail
-          mkdir -p .cargo
-          cat << EOF | tee .cargo/config.toml
-          [target.x86_64-apple-darwin]
-          rustflags = [
-            "-C", "link-arg=-undefined",
-            "-C", "link-arg=dynamic_lookup",
-          ]
-          EOF
-
-      - name: Fetch rust dependencies
-        if: >-
-          steps.rust-changes.outputs.run == 'true'
-          && steps.rust-cache.outputs.cache-hit != 'true'
-        shell: bash
-        run: |
-          find . -name Cargo.toml -not -path './oxidation/libparsec_python/*' -exec cargo fetch --verbose --locked --manifest-path \{\} \;
-        timeout-minutes: 20
-
-      # In this step it may look like we're executing `cargo build` 2 time but
-      # the first one is call with `--all-targets` and not the other one.
-      # Why ?
-      # When I was testing, even tho we specify `--all-targets` (meaning to build everything (tests and libs)),
-      # after that step if I do `cargo build` It still as building/linking to be done.
-      - name: Build rust workspace
-        if: >-
-          steps.rust-changes.outputs.run == 'true'
-          && steps.rust-cache.outputs.cache-hit != 'true'
-        shell: bash
-        run: |
-          set -ex
-          cargo build \
-            --locked \
-            --workspace \
-            ${{ env.cargo-exclude-unused-crates }} \
-            --profile ${{ env.CARGO_PROFILE }} \
-            --all-targets
-          cargo build \
-            --locked \
-            --workspace \
-            ${{ env.cargo-exclude-unused-crates }} \
-            --profile ${{ env.CARGO_PROFILE }}
-        timeout-minutes: 50 # MacOS can be really slow to build our rust lib
-
-  ##############################################################################
   #                            🐍 Python tests                                 #
   ##############################################################################
 
   test-python-matrix:
-    needs: rust-prebuild-matrix
     strategy:
       fail-fast: false
       matrix:
@@ -328,13 +227,8 @@ jobs:
           pwd
           echo "$(pwd)\winfsp-test" >> "$GITHUB_PATH"
 
-      - uses: ./.github/actions/setup-rust
+      - uses: actions-rust-lang/setup-rust-toolchain@v1.3.4
         if: steps.python-changes.outputs.run == 'true'
-        with:
-          version: ${{ env.rust-version }}
-          cache-key: integration
-          os: ${{ matrix.os }}
-        timeout-minutes: 10
 
       - uses: ./.github/actions/setup-python-poetry
         if: steps.python-changes.outputs.run == 'true'
@@ -342,10 +236,6 @@ jobs:
         with:
           python-version: ${{ env.python-version }}
           poetry-version: ${{ env.poetry-version }}
-
-      - name: Install python deps
-        if: steps.python-changes.outputs.run == 'true'
-        run: poetry install -E core -E backend
 
       - name: Debug python & pip version
         if: steps.python-changes.outputs.run == 'true'
@@ -355,6 +245,12 @@ jobs:
           set -x
           poetry run python --version
           poetry run pip --version
+
+      - name: Install python deps
+        if: steps.python-changes.outputs.run == 'true'
+        run: poetry install -E core -E backend
+        env:
+          CARGO_PROFILE: ${{ env.CARGO_PROFILE }}
 
       - name: Basic tests
         if: steps.python-changes.outputs.run == 'true'
@@ -400,7 +296,6 @@ jobs:
   ##############################################################################
 
   test-rust-matrix:
-    needs: rust-prebuild-matrix
     strategy:
       fail-fast: false
       matrix:
@@ -429,157 +324,128 @@ jobs:
         run: echo "run=true" >> $GITHUB_OUTPUT
         shell: bash
 
-      - uses: ./.github/actions/setup-rust
+      - uses: actions-rust-lang/setup-rust-toolchain@v1.3.4
         if: steps.rust-changes.outputs.run == 'true'
-        with:
-          version: ${{ env.rust-version }}
-          cache-key: integration
-          os: ${{ matrix.os }}
-        timeout-minutes: 10
-
-      # Pyo3 need additional configuration on MacOS to be manually build
-      # see https://pyo3.rs/v0.17.3/building_and_distribution.html#macos
-      - name: (🍎 macOS) Configure cargo for PyO3
-        if: >-
-          steps.rust-changes.outputs.run == 'true'
-          && startsWith(matrix.os, 'macos-')
-        shell: bash
-        run: |
-          set -eux
-          set -o pipefail
-          mkdir -p .cargo
-          cat << EOF | tee .cargo/config.toml
-          [target.x86_64-apple-darwin]
-          rustflags = [
-            "-C", "link-arg=-undefined",
-            "-C", "link-arg=dynamic_lookup",
-          ]
-          EOF
-
-      - name: Build rust test codebase
-        if: steps.rust-changes.outputs.run == 'true'
-        shell: bash
-        run: cargo test --workspace --profile ${{ env.CARGO_PROFILE }} ${{ env.cargo-exclude-unused-crates }} --no-run
 
       - name: Test rust codebase
         if: steps.rust-changes.outputs.run == 'true'
         shell: bash
         run: |
           set -ex
+          cargo test --profile ${{ env.CARGO_PROFILE }}  --workspace --features mock-time ${{ env.cargo-exclude-unused-crates }} --exclude libparsec_crypto
           cargo test --profile ${{ env.CARGO_PROFILE }} --package libparsec_crypto --features use-sodiumoxide --no-default-features
           cargo test --profile ${{ env.CARGO_PROFILE }} --package libparsec_crypto --features use-rustcrypto --no-default-features
-          cargo test --profile ${{ env.CARGO_PROFILE }} ${{ env.cargo-exclude-unused-crates }} --workspace --features mock-time --exclude libparsec_crypto
 
-  ##############################################################################
-  #                            🐜 Wasm tests                                   #
-  ##############################################################################
+  # ##############################################################################
+  # #                            🐜 Wasm tests                                   #
+  # ##############################################################################
 
-  test-wasm:
-    runs-on: ubuntu-20.04
-    # We're using a matrix, because we need to have a list to configure:
-    # - The job `Check changed files` (To watch if the specified crate we're changed).
-    # - The job `Run WasmPack test` (where we run the test on each specified crate).
-    # So it's simpler to have only 1 list to maintain (DRY).
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - crate_to_test:
-              - oxidation/libparsec/crates/platform_async
-              - oxidation/libparsec/crates/platform_web
-    name: 🐜 Wasm tests
-    env:
-      WASM_PACK_VERSION: 0.10.3
-      NAVIGATORS: >-
-        firefox
-        chrome
-    steps:
-      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin v3.1.0
+  # test-wasm:
+  #   runs-on: ubuntu-20.04
+  #   # We're using a matrix, because we need to have a list to configure:
+  #   # - The job `Check changed files` (To watch if the specified crate we're changed).
+  #   # - The job `Run WasmPack test` (where we run the test on each specified crate).
+  #   # So it's simpler to have only 1 list to maintain (DRY).
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - crate_to_test:
+  #             - oxidation/libparsec/crates/platform_async
+  #             - oxidation/libparsec/crates/platform_web
+  #   name: 🐜 Wasm tests
+  #   env:
+  #     WASM_PACK_VERSION: 0.10.3
+  #     NAVIGATORS: >-
+  #       firefox
+  #       chrome
+  #   steps:
+  #     - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin v3.1.0
 
-      - name: Check changed files
-        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50  # pin v2.11.1
-        id: changes
-        with:
-          filters: |
-            wasm: ${{ toJSON(matrix.crate_to_test) }}
-            github:
-              - .github/**
+  #     - name: Check changed files
+  #       uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50  # pin v2.11.1
+  #       id: changes
+  #       with:
+  #         filters: |
+  #           wasm: ${{ toJSON(matrix.crate_to_test) }}
+  #           github:
+  #             - .github/**
 
-      - name: Check modified path that require wasm-pack-ci run
-        id: wasm-pack-changes
-        if: >-
-          steps.changes.outputs.wasm == 'true'
-          || steps.changes.outputs.github == 'true'
-          || github.ref == 'refs/head/master'
-        run: echo "run=true" >> $GITHUB_OUTPUT
-        shell: bash
+  #     - name: Check modified path that require wasm-pack-ci run
+  #       id: wasm-pack-changes
+  #       if: >-
+  #         steps.changes.outputs.wasm == 'true'
+  #         || steps.changes.outputs.github == 'true'
+  #         || github.ref == 'refs/head/master'
+  #       run: echo "run=true" >> $GITHUB_OUTPUT
+  #       shell: bash
 
-      - uses: ./.github/actions/setup-rust
-        if: steps.wasm-pack-changes.outputs.run == 'true'
-        with:
-          version: ${{ env.rust-version }}
-          target: wasm32-unknown-unknown
-          os: wasm32-ubuntu-20.04
+  #     - uses: ./.github/actions/setup-rust
+  #       if: steps.wasm-pack-changes.outputs.run == 'true'
+  #       with:
+  #         version: ${{ env.rust-version }}
+  #         target: wasm32-unknown-unknown
+  #         os: wasm32-ubuntu-20.04
 
-      - name: Install Wasm-Pack
-        if: steps.wasm-pack-changes.outputs.run == 'true'
-        run: |
-          set -eux
-          mkdir -p ~/.local/bin
-          cd ~/.local/bin
-          wget https://github.com/rustwasm/wasm-pack/releases/download/v${{ env.WASM_PACK_VERSION }}/wasm-pack-v${{ env.WASM_PACK_VERSION }}-x86_64-unknown-linux-musl.tar.gz -O ~/wasm-pack.tar.gz
-          tar xzf ~/wasm-pack.tar.gz --directory ~/.local/bin --strip-components=1
-          chmod +x ~/.local/bin/wasm-pack
-          echo ~/.local/bin >> "$GITHUB_PATH"
-          ~/.local/bin/wasm-pack --version
+  #     - name: Install Wasm-Pack
+  #       if: steps.wasm-pack-changes.outputs.run == 'true'
+  #       run: |
+  #         set -eux
+  #         mkdir -p ~/.local/bin
+  #         cd ~/.local/bin
+  #         wget https://github.com/rustwasm/wasm-pack/releases/download/v${{ env.WASM_PACK_VERSION }}/wasm-pack-v${{ env.WASM_PACK_VERSION }}-x86_64-unknown-linux-musl.tar.gz -O ~/wasm-pack.tar.gz
+  #         tar xzf ~/wasm-pack.tar.gz --directory ~/.local/bin --strip-components=1
+  #         chmod +x ~/.local/bin/wasm-pack
+  #         echo ~/.local/bin >> "$GITHUB_PATH"
+  #         ~/.local/bin/wasm-pack --version
 
-      - name: Run WasmPack test
-        if: steps.wasm-pack-changes.outputs.run == 'true'
-        run: |
-          set -eu
-          for crate_to_test in ${{ join(matrix.crate_to_test.*, ' ') }}; do
-            for navigator in ${{ env.NAVIGATORS }}; do
-              echo "###################################"
-              echo "# Running WASM test"
-              echo "#   navigator: $navigator"
-              echo "#   crate: $crate_to_test"
-              echo "###################################"
+  #     - name: Run WasmPack test
+  #       if: steps.wasm-pack-changes.outputs.run == 'true'
+  #       run: |
+  #         set -eu
+  #         for crate_to_test in ${{ join(matrix.crate_to_test.*, ' ') }}; do
+  #           for navigator in ${{ env.NAVIGATORS }}; do
+  #             echo "###################################"
+  #             echo "# Running WASM test"
+  #             echo "#   navigator: $navigator"
+  #             echo "#   crate: $crate_to_test"
+  #             echo "###################################"
 
-              (set -x; wasm-pack test --headless --$navigator $crate_to_test)
-            done
-          done
+  #             (set -x; wasm-pack test --headless --$navigator $crate_to_test)
+  #           done
+  #         done
 
 
-  ##############################################################################
-  #                            🌐 Web tests                                    #
-  ##############################################################################
+  # ##############################################################################
+  # #                            🌐 Web tests                                    #
+  # ##############################################################################
 
-  test-web-app:
-    runs-on: ubuntu-22.04
-    name: 🌐 Web tests
-    steps:
-      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin v3.1.0
+  # test-web-app:
+  #   runs-on: ubuntu-22.04
+  #   name: 🌐 Web tests
+  #   steps:
+  #     - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin v3.1.0
 
-      - uses: ./.github/actions/paths-filter
-        id: changes
+  #     - uses: ./.github/actions/paths-filter
+  #       id: changes
 
-      - name: Check modified path that require `test-web` to run
-        id: web-change
-        if: >-
-          steps.changes.outputs.client-web == 'true'
-          || steps.changes.outputs.client-common == 'true'
-          || github.ref == 'refs/heads/master'
-        run: echo "run=true" >> $GITHUB_OUTPUT
-        shell: bash
+  #     - name: Check modified path that require `test-web` to run
+  #       id: web-change
+  #       if: >-
+  #         steps.changes.outputs.client-web == 'true'
+  #         || steps.changes.outputs.client-common == 'true'
+  #         || github.ref == 'refs/heads/master'
+  #       run: echo "run=true" >> $GITHUB_OUTPUT
+  #       shell: bash
 
-      - name: Install dependencies
-        if: steps.web-change.outputs.run == 'true'
-        run: npm clean-install
-        working-directory: oxidation/client
+  #     - name: Install dependencies
+  #       if: steps.web-change.outputs.run == 'true'
+  #       run: npm clean-install
+  #       working-directory: oxidation/client
 
-      # Replace it with `npm run test:unit && npm run test:e2e` when those are stable.
-      # Then move this step to package-ci.yml
-      - name: Build WebApp
-        if: steps.web-change.outputs.run == 'true'
-        run: npm run web:release
-        working-directory: oxidation/client
+  #     # Replace it with `npm run test:unit && npm run test:e2e` when those are stable.
+  #     # Then move this step to package-ci.yml
+  #     - name: Build WebApp
+  #       if: steps.web-change.outputs.run == 'true'
+  #       run: npm run web:release
+  #       working-directory: oxidation/client
