feat(release): Remove the checksums file from the release assets
They are replaced with a single file `checksums.sha256` that contain the
checksum of all uploaded assets since you can easily validate those file
with the command `sha256sum`.

Co-authored-by: Marcos Medrano <786907+mmmarcos@users.noreply.github.com>

diff --git a/.github/workflows/releaser.yml b/.github/workflows/releaser.yml
--- a/.github/workflows/releaser.yml
+++ b/.github/workflows/releaser.yml
@@ -160,19 +160,23 @@ jobs:
             echo "local=${{ needs.version.outputs.local }}";
           ) | tee release-files/version
 
-      - name: Generate checksums file released files
-        run: sha256sum release-files/* | sed 's;release-files/;;' | tee checksums.sha256
-
-      - name: Extract checksum for each file
-        run: |
-          set -x
-          # Every files that don't end with '.sha256'
-          for file in $(find release-files -type f -not -name '*.sha256'); do
-            grep "$(basename "$file")" checksums.sha256 | cut -d ' ' -f 1 > "$file".sha256
-          done
-
       - name: List files in 'release-files'.
         run: tree release-files
+
+      - name: Generate checksums file for released files
+        run: sha256sum * | tee ../checksums.sha256
+        working-directory: release-files
+
+      - name: Generate data for release
+        id: info
+        shell: bash -e -o pipefail {0}
+        run: |
+          (
+            echo 'tag_name=${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'nightly' || github.ref }}'
+            echo 'release_name=${{ env.NIGHTLY_RELEASE == 'true' && 'Nightly release' || format('Release v{0}', needs.version.outputs.full) }}'
+            echo 'repo_path=${{ github.server_url }}/${{ github.repository }}'
+          ) | tee -a $GITHUB_OUTPUT
+        timeout-minutes: 1
 
       - name: Generate summary
         id: summary
@@ -183,13 +187,25 @@ jobs:
             echo "output<<$EOF"
             echo '# Parsec ${{ needs.version.outputs.full }}'
             echo
-            echo 'You can find all assets checksums below, or use `<asset name>.sha256`'
+            echo '## Verifying the assets'
+            echo
+            echo 'You can verify the downloaded assets with the following command:'
+            echo
+            echo '```shell'
+            echo 'sha256sum -c checksums.sha256 --ignore-missing'
+            echo '```'
+            echo
+            echo '> The Windows files does not have a checksum because they are signed manually'
+            echo
+            echo 'You can [download `checksums.sha256`](${{ steps.info.outputs.repo_path }}/releases/download/${{ steps.info.outputs.tag_name }}/checksums.sha256) or copy the following content into `checksums.sha256`:'
             echo
             echo '```txt'
             cat checksums.sha256
             echo '```'
             echo
-            echo 'Generated by <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>'
+            echo ---
+            echo
+            echo 'Generated by <${{ steps.info.outputs.repo_path }}/actions/runs/${{ github.run_id }}>'
             echo "$EOF"
           ) | tee -a $GITHUB_OUTPUT
 
@@ -202,7 +218,7 @@ jobs:
             echo "No nightly release to remove"
           fi
         env:
-          GH_ARGS: --repo=${{ github.server_url}}/${{ github.repository }}
+          GH_ARGS: --repo=${{ steps.info.outputs.repo_path }}
           GH_TOKEN: ${{ github.token }}
 
       - name: Checkout the repository to update the nightly tag
@@ -225,26 +241,23 @@ jobs:
         uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # pin v2.2.1
         with:
           draft: ${{ env.NIGHTLY_RELEASE != 'true' }}
-          tag_name: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'nightly' || github.ref }}
+          tag_name: ${{ steps.info.outputs.tag_name }}
           body: ${{ steps.summary.outputs.output }}
           prerelease: ${{ needs.version.outputs.pre != '' || needs.version.outputs.dev != '' || needs.version.outputs.local != '' }}
-          name: ${{ env.NIGHTLY_RELEASE == 'true' && 'Nightly release' || format('Release v{0}', needs.version.outputs.full) }}
+          name: ${{ steps.info.outputs.release_name }}
           # release-files/Parsec_${{ needs.version.outputs.full }}_win_*.exe*
           files: |
-            release-files/parsec_cloud-${{ needs.version.outputs.pep440 }}-*.whl*
-            release-files/Parsec_${{ needs.version.outputs.full }}_linux_*.AppImage*
-            release-files/Parsec_${{ needs.version.outputs.full }}_linux_*.snap*
-            release-files/Parsec_${{ needs.version.outputs.full }}_mac_*.dmg*
-            release-files/Parsec_${{ needs.version.outputs.full }}_mac_*.zip*
+            release-files/parsec_cloud-${{ needs.version.outputs.pep440 }}-*.whl
+            release-files/Parsec_${{ needs.version.outputs.full }}_linux_*.AppImage
+            release-files/Parsec_${{ needs.version.outputs.full }}_linux_*.snap
+            release-files/Parsec_${{ needs.version.outputs.full }}_mac_*.dmg
+            release-files/Parsec_${{ needs.version.outputs.full }}_mac_*.zip
             release-files/parsec-cli_${{ needs.version.outputs.full }}_linux-x86_64-*
             release-files/python-*-requirements.txt
-            release-files/python-*-requirements.txt.sha256
             release-files/latest-*.yml
-            release-files/latest-*.yml.sha256
             release-files/Parsec-SBOM-*.spdx.json
-            release-files/Parsec-SBOM-*.spdx.json.sha256
             release-files/version
-            release-files/version.sha256
+            checksums.sha256
           fail_on_unmatched_files: true
           generate_release_notes: false
         timeout-minutes: 5
